import { Injectable } from '@angular/core';

@Injectable()
export class FeedService {

  private _data = [
    {
      type: 'geo-message',
      author: 'Kostya',
      surname: 'Danovsky',
      header: 'Earned Marketing Commission',
      text: '"Received N15,600.00 marketing commission on sale of 280m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 11:55 pm',
      ago: '25 minutes ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Andrey',
      surname: 'Hrabouski',
      header: 'Earned Marketing Commission',
      text: '"Received N35,760.00 marketing commission on sale of 450m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 9:30 pm',
      ago: '3 hrs ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Vlad',
      surname: 'Lugovsky',
      header: 'Earned Membership Commission',
      text: '"Received N598 membership commission on investment of 5m2in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: 'Today 2:20 pm',
      ago: '10 hrs ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nasta',
      surname: 'Linnie',
      header: 'Earned Marketing Commission',
      text: '"Received N9,760.00 marketing commission on sale of 48m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '11.11.2015',
      ago: '2 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nick',
      surname: 'Cat',
      header: 'Earned Membership Commission',
      text: '"Received N1,760.00 membership commission on sale of 48m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '11.11.2015',
      ago: '2 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Vlad',
      surname: 'Lugovsky',
      header: 'Earned Marketing Commission',
      text: '"Received N9,760.00 marketing commission on sale of 48m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '12.11.2015',
      ago: '3 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Andrey',
      surname: 'Hrabouski',
      header: 'Earned Marketing Commission',
      text: '"Received N760.00 marketing commission on sale of 8m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '14.11.2015',
      ago: '5 days ago',
      expanded: false,
    }, {
      type: 'geo-message',
      author: 'Nasta',
      surname: 'Linnie',
      header: 'Earned Marketing Commission',
      text: '"Received N990.00 marketing commission on sale of 18m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '14.11.2015',
      ago: '5 days ago',
      expanded: false,
    }, {
      type: 'image-message',
      author: 'Alexander',
      surname: 'Demeshko',
      header: 'Meet this weeks top marketer.',
      text: '"Alex sold 5,233m2 of land this week alone to earn the top marketer position and claim the N10,000.00 bonus"',
      preview: 'app/feed/lands/man_cheque.jpeg',
      link: 'http://localhost:4200/#/pages/home',
      time: '15.11.2015',
      ago: '6 days ago',
      expanded: false,
    }, {
      type: 'video-message',
      author: 'Nick',
      surname: 'Cat',
      header: 'How to boost your membership commission',
      text: 'Watch this insightful video to learn how membership commissions work and what you can do to earn more',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '16.11.2015',
      ago: '7 days ago',
      expanded: false,
    },
    {
      type: 'text-message',
      author: 'Kostya',
      surname: 'Danovsky',
      header: 'Earned Marketing Commission',
      text: '"Received N1,260.00 marketing commission on sale of 40m2of land in Ebute-Lekki, Ibeju Lekki, Lagos"',
      preview: 'app/feed/lands/land_ebute_lekki_304000m2.png',
      link: 'http://localhost:4200/#/pages/home',
      time: '18.11.2015',
      ago: '9 days ago',
      expanded: false,
    },
  ];

  getData() {
    return this._data;
  }
}
